model_name: yolov8n.pt
imgsz: 960
epochs: 100
batch: 8
workers: 4
device: cpu
project: runs/train
name: visdrone-yolov8n
patience: 20
cache: false
optimizer: auto
close_mosaic: 10
seed: 42
deterministic: true
pretrained: true
exist_ok: true
single_cls: false
degrees: 0.0
translate: 0.1
scale: 0.5
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
